
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/accounts}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:devopspassword}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
